name: artifact

on:
  workflow_dispatch:

jobs:
  upload-and-download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: mkdir -p ./artifact

    - run: echo hello > ./artifact/world.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./artifact/world.txt

    - uses: actions/download-artifact@v3
      with:
        name: my-artifact

    - name: PWD
      run: echo ${{ github.workspace }}

    - name: Display structure of downloaded files
      run: ls -R
  download:
    needs: [ upload-and-download ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact

      - name: PWD
        run: echo ${{ github.workspace }}

      - name: Display structure of downloaded files
        run: ls -R
