name: env

on:
  workflow_dispatch:
    inputs:
      aksk:
        description: aksk
        type: string
        required: true
    canary_enabled:
        description: Enable canary deployment with the lastet build
        type: boolean
        default: "false"
        required: true
  push:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CANARY_ENABLED: ${{ inputs.canary_enabled }}

jobs:
  env-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Build Number
        run: |
          echo "test=123" >> $GITHUB_ENV

      - name: Echo boolean
        timeout-minutes: 5
        run: |
          echo ${{ inputs.canary_enabled }}
          echo ${{ env.CANARY_ENABLED }}

      - name: Set current_branch environment
        run: echo "current_branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"

      - name: Add bin to path
        run: echo "/usr/local/bin/test" >> $GITHUB_PATH

      - name: Split string
        run: |
          IN='${{ inputs.aksk }}'
          IFS=';' read -ra ADDR <<< "$IN"; unset IFS;
          echo "${ADDR[0]##*export }" >> env.list
          echo "${ADDR[1]##*export }" >> env.list
          echo "${ADDR[2]##*export }" >> env.list
          echo "${ADDR[3]##*export }" >> env.list

      - name: Show
        run: |
          cat env.list

      - name: Upload env list
        uses: actions/upload-artifact@v3.1.2
        with:
          name: env
          path: "env.list"
