name: env

on:
  workflow_dispatch:
    inputs:
      aksk:
        description: aksk
        type: string
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  env-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Run inputs
        run: |
          echo ${{ inputs.aksk }}

      - name: Set Build Number
        timeout-minutes: 5
        run: |
          echo "test=123" >> $GITHUB_ENV

      - name: Set current_branch environment
        run: echo "current_branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"

      - name: Add bin to path
        run: echo "/usr/local/bin/test" >> $GITHUB_PATH

      - name: Variables
        id: variables
        uses: actions/github-script@v6.4.1
        with:
          script: |
            const aksk = ${{ inputs.aksk }};
            console.log(aksk);

            const aksk2 = core.getInput('aksk');
            console.log(aksk2);

            const AWS_ACCESS_KEY_ID = aksk.split(';')[0].split('=')[1].split('\"')[1]};
            const AWS_SECRET_ACCESS_KEY = aksk.split(';')[0].split('=')[1].split('\"')[1]};
            const AWS_SESSION_TOKEN = aksk.split(';')[0].split('=')[1].split('\"')[1]};
            const AWS_SECURITY_TOKEN = aksk.split(';')[0].split('=')[1].split('\"')[1]};

            core.exportVariable('AWS_ACCESS_KEY_ID', AWS_ACCESS_KEY_ID);
            core.exportVariable('AWS_SECRET_ACCESS_KEY', AWS_SECRET_ACCESS_KEY);
            core.exportVariable('AWS_SESSION_TOKEN', AWS_SESSION_TOKEN);
            core.exportVariable('AWS_SECURITY_TOKEN', AWS_SECURITY_TOKEN);

      - name: Show
        run: |
          echo $GITHUB_ENV
          echo $GITHUB_PATH
