name: env

on:
  workflow_dispatch:
    inputs:
      aksk:
        description: aksk
        type: string
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  env-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.1

      - name: Set Build Number
        timeout-minutes: 5
        run: |
          echo "test=123" >> $GITHUB_ENV

      - name: Set current_branch environment
        run: echo "current_branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"

      - name: Add bin to path
        run: echo "/usr/local/bin/test" >> $GITHUB_PATH

      - name: Split aksk
        run: |
          echo "a=$(echo ${{ inputs.aksk }} | cut -d ";" -f 1)" >> "$GITHUB_ENV"
          echo ${{ env.a }}

      - name: Show
        run: |
          echo $GITHUB_ENV
          echo $GITHUB_PATH
