name: env

on:
  workflow_dispatch:
    inputs:
      aksk:
        description: aksk
        type: string
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  env-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Build Number
        run: |
          echo "test=123" >> $GITHUB_ENV

      - name: Set current_branch environment
        run: echo "current_branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"

      - name: Add bin to path
        run: echo "/usr/local/bin/test" >> $GITHUB_PATH

      - name: Split string
        run: |
          IN='${{ inputs.aksk }}'
          IFS=';' read -ra ADDR <<< "$IN"; unset IFS;
          echo "${ADDR[0]##*export }" >> env.list
          echo "${ADDR[1]##*export }" >> env.list
          echo "${ADDR[2]##*export }" >> env.list
          echo "${ADDR[3]##*export }" >> env.list

      - name: Show
        run: |
          cat env.list
