name: build number

on:
  workflow_dispatch:

jobs:
  build_number:
    runs-on: ubuntu-latest
    steps:
    - name: Generate build number
      uses: onyxmueller/build-tag-number@v1
      with:
        token: ${{ github.token }}
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"