name: build number
run-name: $BUILD_NUMBER

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_number:
    runs-on: ubuntu-latest
    steps:
    - name: Generate build number
      uses: onyxmueller/build-tag-number@v1
      with:
        token: ${{ secrets.github_token }}

    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"

    - name: Print github.run_number
      run: echo ${{ github.run_number }}