name: Caching

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p ./artifact
      - run: echo hello > ./artifact/world.txt
      - run: echo hello2 > ./artifact/world2.txt
      - name: Display structure of files
        run: ls -R

      - name: Cache files
        id: cache-file
        uses: actions/cache@v3
        with:
          key: world_txt
          path: |
            ./artifact/world*.txt

      - if: ${{ steps.cache-file.outputs.cache-hit != 'true' }}
        name: Display structure of files
        continue-on-error: true
        run: ls -R

  download:
    needs: [ upload ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache files
        uses: actions/cache@v3
        with:
          key: world_txt
          path: |
            ./artifact/world*.txt
      - name: PWD
        run: echo ${{ github.workspace }}
      - name: Display structure of downloaded files
        run: ls -R
