name: Caller Common Action

on:
  workflow_dispatch:
    inputs:
      sites:
        description: int, staging
        type: string
        required: true
        default: "int staging"

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
    - name: Set current_branch environment
      shell: bash
      run: echo "current_branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"

    - name: Call example
      uses: BalinLin/common-action/.github/workflows/called_example.yml@main
      with:
        sites: ${{ env.current_branch }}

  myjob:
    runs-on: ubuntu-latest
    needs: call
    steps:
      - name: ls
        run: |
          ls -l
