name: Caller Common Action

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  call:
    uses: BalinLin/common-action/.github/workflows/called_example.yml@main
    with:
      build_branch_call: ${{ github.ref_name }}
