name: Caller

on:
  workflow_dispatch:
    inputs:
      sites:
        description: staging, usqa, twib, dev, xdr, sre, xdr_beta, xdr_s_u, se.
        type: string
        required: true
        default: "staging usqa twib dev xdr sre xdr_beta xdr_s_u se"

jobs:
  call:
    uses: ./.github/workflows/called.yml
    with:
      sites: ${{ inputs.sites }}
  myjob:
    runs-on: ubuntu-latest
    needs: call
    steps:
      - name: Reusing workflows
        run: |
          ls -l
          echo "${{ env.passedEnv }}"
