name: Caller Common Action

on:
  workflow_dispatch:
    inputs:
      sites:
        description: int, staging
        type: string
        required: true
        default: "int staging"

jobs:
  call:
    uses: BalinLin/common-action/.github/workflows/called_example.yml@main
    with:
      sites: ${{ inputs.sites }}
  myjob:
    runs-on: ubuntu-latest
    needs: call
    environment:
      name: prod
      url: ${{ github.server_url }}/${{ github.repository }}/wiki
    steps:
      - name: Reusing workflows
        run: |
          ls -l
          echo "${{ env.passedEnv }}"

