name: Called

on:
  workflow_call:
    inputs:
      sites:
        required: true
        type: string

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
      - name: Reusing workflows
        run: |
          echo "passedEnv=${{ inputs.sites }}" >> $GITHUB_ENV
          ls -l

      - name: passedEnv echo
        run: echo "${{ env.passedEnv }}"

      - name: echo txt
        run: echo "test" >> test.txt

      - name: Upload txt
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test.txt
          path: "test.txt"