name: Called

on:
  workflow_call:
    inputs:
      sites:
        required: true
        type: string

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
      - name: Reusing workflows
        run: |
          echo "passedEnv=${{ inputs.sites }}" >> $GITHUB_ENV
          ls -l
          echo "${{ env.passedEnv }}"
