name: Checkout v3.5.0

on:
  workflow_dispatch:

env:
  BUILD_BRANCH: "dev"

jobs:
  enigma-deploy-int:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
        with:
          ref: ${{ env.BUILD_BRANCH }}

      - name: Set Build Number
        run: echo "::set-env name=BUILD_NUMBER::${{ github.run_number }}"
