name: checkout

on:
  workflow_dispatch:

jobs:
  env-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Checkout
        uses: actions/checkout@v3.5.0
        with:
          repository: ${{github.repository}}.wiki

      - name: Display structure of files
        run: ls -Ra