name: Checkout v3.5.0

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: Last success build number of enigma.
        type: string
        required: true

env:
  BUILD_BRANCH: "dev"

jobs:
  enigma-deploy-int:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
        with:
          ref: ${{ env.BUILD_BRANCH }}

      - name: Set Build Number
        run: |
          echo "run number - ${{ github.run_number }}"
          echo "build number - ${{ inputs.build_number }}"
        # run: echo "{environment_variable_name}={value}" >> $GITHUB_ENV
        # run: echo "::set-env name=BUILD_NUMBER::${{ github.run_number }}"
