name: composite

on:
  workflow_dispatch:

jobs:
  composite-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Set Build Number
        timeout-minutes: 5
        run: |
          echo "test=123" >> $GITHUB_ENV

      - id: foo
        uses: ./.github/composite-actions/test
        with:
          who-to-greet: 'Mona the Octocat'

      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

      - name: Show
        run: |
          printenv

