name: container

on:
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: hello-world
    # services:
    #   postgres:
    #     image: postgres
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: echo test