name: cron

on:
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Echo ${{ github.ref_name }}
        run: echo ${{ github.ref_name }}
