name: docker with ansible

on:
  workflow_dispatch:

jobs:
  playbook:
    runs-on: ubuntu-latest
    container:
      image: aws.registry.trendmicro.com/dddops-public/deploy-toolkit-aws:int
      credentials:
        username: ${{ secrets.DEPLOY_USER }}
        password: ${{ secrets.DEPLOY_CLI }}
      # volumes:
        # ${{ github.workspace }}:${{ github.workspace }}
    steps:
    # - name: container
    #   run: |
    #     docker ps -a
    #     docker images
    #     docker run --rm aws.registry.trendmicro.com/dddops-public/deploy-toolkit-aws:int
    #     docker rmi aws.registry.trendmicro.com/dddops-public/deploy-toolkit-aws:int
    #     docker ps -a
    #     docker images

    - name: echo 1
      run: |
        ls -l
        echo $PWD
        printenv

    - name: check out
      uses: actions/checkout@v3

    - name: echo 2
      run: |
        ls -l
        echo $PWD
        printenv

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: local_playbook.yml
        # Optional, directory where playbooks live
        directory: /__w/ga/ga/ansible
        # Optional, additional flags to pass to ansible-playbook
        options: |
          --inventory hosts
          --extra-vars hello=there
          --verbose