name: docker with ansible

on:
  workflow_dispatch:

env:
  HARBOR_REGISTRY: "aws.registry.trendmicro.com"
  HARBOR_IMAGE: "dddops-public/deploy-toolkit-aws"
  HARBOR_BRANCH: "int"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: check out
      uses: actions/checkout@v3.5.0

    - name: echo 1
      run: |
        ls -l
        echo $PWD
        printenv

    - name: Run docker
      uses: nick-fields/retry@v2.8.3
      env:
        deploy_toolkit: |
          docker run --privileged --rm --net=host \
                    -v /var/run/docker.sock:/var/run/docker.sock \
                    -v "${{ github.workspace }}":$HOME \
                    -w $HOME/ansible \
                    hello-world
        command: |
          ls -l && echo $PWD
      with:
        timeout_minutes: 10
        max_attempts: 2
        command: |
          ${{ env.deploy_toolkit }}

    - name: Pre Deploy - Build
      timeout-minutes: 10
      run: |
        echo ${{ env.deploy_toolkit }}
        echo ${{ env.command }}
        echo ${{ env.deploy_toolkit }} ${{ env.command }}
        printenv

      env:
        deploy_toolkit: |
          docker run --privileged --rm --net=host \
                    -v /var/run/docker.sock:/var/run/docker.sock \
        command: |
          ansible-playbook -i inventory/test \
                    deploy_build.yml \
                    -v --extra-vars \
                    ' \
                    devops_tools_branch="devops" \
                    devops_tools_build_number="123" \
                    '; \