name: docker with ansible

on:
  workflow_dispatch:

env:
  HARBOR_REGISTRY: "aws.registry.trendmicro.com"
  HARBOR_IMAGE: "dddops-public/deploy-toolkit-aws"
  HARBOR_BRANCH: "int"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Harbor
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.HARBOR_REGISTRY }}
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_CLI }}

    - name: check out
      uses: actions/checkout@v3.5.0

    - name: echo 1
      run: |
        ls -l
        echo $PWD
        printenv

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run docker
        env:
          deploy_toolkit: |
            docker run --privileged --rm --net=host \
                      -v /var/run/docker.sock:/var/run/docker.sock \
                      -v "${{ github.workspace }}":$HOME \
                      -w $HOME/ga/test \
                      ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_IMAGE }}:${{ env.HARBOR_BRANCH }} \
          command: |
            aws --version

        run: |
          ${{ env.deploy_toolkit }} ${{ env.command }}

      - name: echo 2
        run: |
          ls -l
          echo $PWD
          printenv

      - name: Run docker 2
        env:
          deploy_toolkit: |
            docker run --privileged --rm --net=host \
                      -v /var/run/docker.sock:/var/run/docker.sock \
                      -v "${{ github.workspace }}":$HOME \
                      -w $HOME/ga/test \
                      ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_IMAGE }}:${{ env.HARBOR_BRANCH }} \
          command: |
            aws --version

        run: |
          ${{ env.deploy_toolkit }} ${{ env.command }}
