name: boolean

on:
  workflow_dispatch:
    inputs:
      sites:
        description: staging usqa twib dev xdr sre xdr_beta xdr_s_u se
        type: string
        required: true
        default: "dev"
      build_branch:
        description: Decide from which code branch
        type: choice
        required: true
        default: "dev"
        options:
        - dev
        - master
        - ui2
        - virtual-flow
      build_number:
        description: Last success build number of enigma
        type: string
        required: true
        default: "2685"
      canary_enabled:
        description: Enable canary deployment with the lastet build
        type: boolean
        default: "false"
      canary_weight:
        description: The percentage of the traffics to be deployed
        type: choice
        default: "0.05"
        options:
        - 0.05
        - 0.1
        - 0.15
        - 0.2
        - 0.25
        - 0.3
        - 0.35
        - 0.4
        - 0.45
        - 0.5
        - 0.55
        - 0.6
        - 0.65
        - 0.7
        - 0.75
        - 0.8
        - 0.85
        - 0.9
        - 0.95

env:
  CANARY_ENABLED: ${{ inputs.canary_enabled }}

jobs:
  env-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo boolean
        timeout-minutes: 5
        run: |
          echo ${{ inputs.canary_enabled }}
          echo ${{ env.CANARY_ENABLED }}

