name: masking

on:
  workflow_run:
    workflows: [json]
    types:
      - completed

jobs:
  generate-a-secret-output:
    runs-on: ubuntu-latest
    steps:
      - id: sets-a-secret
        name: Generate, mask, and output a secret
        run: |
          the_secret=$((RANDOM))
          echo "::add-mask::$the_secret"
          echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
      - name: Use that secret output (protected by a mask)
        run: |
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"

      - name: Set env
        run: >
          echo "test=
          docker run --privileged --rm --net=host
          -e AWS_ACCESS_KEY_ID=${{ secrets.DEPLOY_BRANCH }}
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.DEPLOY_HARBOR }}
          -v /var/run/docker.sock:/var/run/docker.sock
          -v "${{ github.workspace }}":$HOME
          -w $HOME/ansible
          " >> "$GITHUB_ENV"

      - name: Print env
        run: |
          echo ${{ env.test }}