name: merge_push

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  merge_push:
    runs-on: ubuntu-latest
    steps:
      - name: Echo ${{ github.ref_name }}
        run: echo ${{ github.ref_name }}
