name: Caching show

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-file
        uses: actions/cache@v3
        with:
          path: ./artifact/world.txt
          key: world_txt

      - if: ${{ steps.cache-file.outputs.cache-hit != 'true' }}
        name: Display structure of files
        continue-on-error: true
        run: ls -R

      - name: Display structure of files
        run: ls -R